version: "3"

dotenv:
  - ".env"

tasks:
  lint:
    label: Lint
    desc: Lint
    cmds:
      - alejandra .
  deploy:
    label: Deploy
    desc: Deploy a workstation
    vars:
      WORKSTATION: '{{.WORKSTATION | default "personal"}}'
    cmds:
      - nix run nix-darwin -- switch --flake ".#{{.WORKSTATION}}"
